project:
  name: mytool
  version: 0.1.0
  description: A Python project using uv package manager
  last_updated: '2025-03-27'
environment:
  python_version: 3.12.3
  package_manager: uv
  virtual_env: .venv
dependencies:
  development:
  - pre-commit-placeholder-package @ file:///home/remixonwin/.cache/pre-commit/repo736oite_
  - pyyaml==6.0.2
configuration_files:
- path: pyproject.toml
  purpose: Project metadata and build configuration
  current_state: Configured with basic project info and pytest settings
- path: ruff.toml
  purpose: Ruff linter configuration
  current_state: Set up with standard Python linting rules (E, F, B, I)
- path: .venv
  purpose: Virtual environment
  current_state: Created and configured with uv
source_code:
  main_module:
    path: src/main.py
    status: Created
    features:
    - Basic main() function implemented
    todo: []
  files:
  - path: src/__init__.py
    status: Active
    last_modified: '2025-03-27'
  - path: src/main.py
    status: Active
    last_modified: '2025-03-27'
tests:
  status: Initial setup complete
  files:
  - path: tests/__init__.py
    covers: tests/__init__.py
    last_modified: '2025-03-27'
  - path: tests/test_main.py
    covers: src/main.py
    last_modified: '2025-03-27'
project_structure:
  .github:
    project_tracker.yaml: .github/project_tracker.yaml
    workflows:
      cd.yml: .github/workflows/cd.yml
      ci.yml: .github/workflows/ci.yml
  .hooks:
    update_project_tracker.py: .hooks/update_project_tracker.py
  .pre-commit-config.yaml: .pre-commit-config.yaml
  README.md: README.md
  pyproject.toml: pyproject.toml
  ruff.toml: ruff.toml
  src:
    __init__.py: src/__init__.py
    main.py: src/main.py
  tests:
    __init__.py: tests/__init__.py
    test_main.py: tests/test_main.py
development_workflow:
  formatting:
    tool: black
    status: Configured
    command: black .
    pre_commit: true
  linting:
    tool: ruff
    status: Configured
    command: ruff check .
    pre_commit: true
  testing:
    tool: pytest
    status: Configured
    command: python -m pytest
  pre_commit:
    status: Configured
    hooks:
    - black (formatting)
    - ruff (linting)
    - yaml validation
    - file hygiene checks
git:
  status: Initialized
  tracked_files:
  - All project files
  ignored_patterns:
  - __pycache__
  - .venv
ci_cd:
  ci:
    provider: GitHub Actions
    workflow: .github/workflows/ci.yml
    actions:
    - Run tests (pytest)
    - Code formatting (black)
    - Linting (ruff)
    - Project tracker update
    - Pre-commit checks
    triggers:
    - Push to main/master
    - Pull requests to main/master
  cd:
    provider: GitHub Actions
    workflow: .github/workflows/cd.yml
    actions:
    - Build Python package
    - Publish to PyPI
    triggers:
    - New release published
next_steps:
- Add more comprehensive test coverage
- Set up CI/CD pipeline
- Add project documentation
- Implement core functionality
- Configure PyPI token in GitHub repository secrets
- Update package metadata in pyproject.toml with actual author information
- Create first release to trigger CD pipeline
model_context:
  important_notes:
  - Project uses uv for both package management and virtual environment
  - All development tools are installed in virtual environment
  - Test infrastructure is set up and working
  semantic_context:
    main_purpose: Python tool project with modern development practices
    development_stage: Initial setup complete
    key_files_to_monitor:
    - src/main.py
    - tests/test_main.py
    - pyproject.toml
    - ruff.toml
