repos:
-   repo: local
    hooks:
    -   id: project-tracker
        name: Project Tracker
        entry: .venv/bin/python src/hooks/pre_commit.py
        language: system
        pass_filenames: false
        always_run: true
        stages: [commit]

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.4
    hooks:
    -   id: ruff
        args: [--fix]
    -   id: ruff-format

-   repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
    -   id: black
        language_version: python3
