repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.12

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2
    hooks:
      - id: ruff
        args: [--fix]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements

  - repo: local
    hooks:
      - id: update-project-tracker
        name: Update Project Tracker
        entry: hooks/update_project_tracker.py
        language: python
        additional_dependencies: [PyYAML>=6.0, jsonschema>=4.23.0]
        pass_filenames: false
        always_run: true
        stages: [post-commit]

  - repo: local
    hooks:
      - id: check-docs
        name: Check Documentation
        entry: hooks/check_docs.py
        language: python
        additional_dependencies: [pdoc>=15.0.0]
        pass_filenames: false
        always_run: true
        stages: [pre-commit]

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest with coverage
        entry: pytest
        language: python
        types: [python]
        args: [
          "-v",
          "--cov=hooks",
          "--cov=src",
          "--cov-report=term-missing",
          "--cov-branch",
          "--cov-fail-under=90"
        ]
        additional_dependencies:
          - pytest>=8.0.0
          - pytest-cov>=6.0.0
          - PyYAML>=6.0
          - toml>=0.10.2
          - jsonschema>=4.23.0
        pass_filenames: false
        always_run: true
        stages: [post-commit]  # Run tests after formatting is done
        verbose: true
