[lint]
select = [
    "E",   # pycodestyle
    "F",   # pyflakes
    "I",   # isort
    "UP",  # pyupgrade
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
]
ignore = []

[lint.per-file-ignores]
# Allow unused imports in __init__.py files
"__init__.py" = ["F401"]

[lint.pycodestyle]
max-line-length = 99

[format]
indent-style = "space"
quote-style = "double"
