name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.12"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Set up virtual environment
        run: |
          python -m venv .venv
          . .venv/bin/activate
          python -m pip install --upgrade pip
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          export PATH="$HOME/.local/bin:$PATH"
      - name: Install dependencies
        run: |
          . .venv/bin/activate
          which uv || (echo "uv not found in PATH" && exit 1)
          $HOME/.local/bin/uv pip install -e .[test]
          $HOME/.local/bin/uv pip install pytest pytest-cov black ruff pre-commit PyYAML pdoc
      - name: Run pre-commit
        run: |
          . .venv/bin/activate
          git config --global --add safe.directory /github/workspace
          SKIP=project-tracker pre-commit run --all-files
      - name: Run tests
        run: |
          . .venv/bin/activate
          pytest tests/
      - name: Build documentation
        run: |
          . .venv/bin/activate
          pdoc -o docs/ src/
